services:
  redis:
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge

volumes:
  redis-data:
